config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'widgets#index'

  namespace :users do
    post :sign_up, to: 'registrations#create'
    post :sign_in, to: 'sessions#create'
    delete :sign_out, to: 'sessions#destroy'
  end

  resources :users
  resources :widgets
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/modellable.rb
module Modellable
  def build_widgets(response)
    response.value![:widgets].map do |widget_attrs|
      widget_attrs[:user] = User.new(widget_attrs[:user])
      Widget.new(widget_attrs)
    end
  end
end

app/models/user.rb
class User
  include ActiveModel::Model
  include Modellable

  attr_accessor :id, :first_name, :last_name, :email, :password, :access_token, :refresh_token,
                :images, :name, :date_of_birth, :active

  validates :first_name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, confirmation: true, presence: true
  validates :password_confirmation, presence: true

  class << self
    def show(id:, token:)
      response = ShowoffAPI::Clients::Users.new.show(id: id, token: token)
      return unless response.success?

      new(response.value![:user])
    end

    def current_user(token)
      response = ShowoffAPI::Clients::Users.new.me(token)
      return unless response.success?

      new(response.value![:user])
    end
  end

  def save
    return false unless valid?

    response = ShowoffAPI::Clients::Users.new.create(user: to_valid_params)
    if response.success?
      store_tokens(response) && true
    else
      (errors[:base] << response.failure.body[:message]) && false
    end
  end

  def sign_in
    response = ShowoffAPI::Clients::Users.new.sign_in({ username: email, password: password })
    if response.success?
      store_tokens(response) && true
    else
      (errors[:base] << response.failure.body[:message]) && false
    end
  end

  def widgets(token)
    response = ShowoffAPI::Clients::Users.new.user_widgets(id: id, token: token)
    if response.success?
      build_widgets(response)
    else
      []
    end
  end

  private

  def to_valid_params
    as_json(only: %w[first_name last_name email password])
  end

  def store_tokens(response)
    self.access_token = response.value!.dig(:token, :access_token)
    self.refresh_token = response.value!.dig(:token, :refresh_token)
  end
end

app/models/widget.rb
class Widget
  include ActiveModel::Model

  attr_accessor :id, :name, :description, :kind, :user, :owner

  validates :name, presence: true
  validates :description, presence: true
  validates :kind, presence: true

  def persisted?
    id.present?
  end

  class << self
    include Modellable

    def get_visible(term = nil)
      response = ShowoffAPI::Clients::Widgets.new.visible(term)
      if response.success?
        build_widgets(response)
      else
        []
      end
    end

    def show(id:, token:)
      response = ShowoffAPI::Clients::Widgets.new.show(id: id, token: token)
      return unless response.success?

      new(response.value![:widget])
    end
  end

  def save(access_token)
    return unless valid?

    response = ShowoffAPI::Clients::Widgets.new.create(token: access_token, params: { widget: to_valid_params })
    if response.success?
      self.id = response.value![:widget][:id]
    else
      (errors[:base] << response.failure.body[:message]) && false
    end
  end

  def update(access_token)
    return unless valid?

    response = ShowoffAPI::Clients::Widgets.new.update(token: access_token, id: id, params: { widget: to_valid_params })
    if response.success?
      true
    else
      (errors[:base] << response.failure.body[:message]) && false
    end
  end

  def destroy(access_token)
    response = ShowoffAPI::Clients::Widgets.new.destroy(token: access_token, id: id)
    if response.success?
      true
    else
      (errors[:base] << response.failure.body[:message]) && false
    end
  end

  def owned_by?(user)
    return false unless user

    self.user&.id == user.id
  end

  private

  def to_valid_params
    as_json(only: %w[name description kind])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout proc{ |c| c.request.xhr? ? false : 'application' }

  before_action :authenticate_user!

  protected

  def user_authenticated?
    session[:access_token].present?
  end

  def authenticate_user!
    return true if user_authenticated?

    flash[:notice] = 'Please signin to continue.'
    redirect_to root_path
  end

  def current_user
    return unless user_authenticated?
    @current_user ||= User.current_user(access_token)
  end

  helper_method :user_authenticated?
  helper_method :current_user

  private

  def access_token
    @access_token ||= session[:access_token]
  end

  def refresh_token
    @refresh_token ||= session[:refresh_token]
  end
end

app/controllers/concerns/session_helper.rb
module SessionHelper
  def set_session(user)
    session[:access_token] = user.access_token
    session[:refresh_token] = user.refresh_token
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < ApplicationController
  include SessionHelper
  skip_before_action :authenticate_user!

  def create
    @user = User.new(user_params)
    if @user.save
      set_session(@user)
      redirect_to root_path, notice: 'Succesfully registered as new user.'
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < ApplicationController
  include SessionHelper

  skip_before_action :authenticate_user!, only: [:create]

  def create
    @user = User.new(login_params)
    if @user.sign_in
      set_session(@user)
      redirect_to root_path, notice: 'Succesfully signed in.'
    end
  end

  def destroy
    reset_session
    redirect_to root_path, notice: 'You have been logged out.'
  end

  private

  def login_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.show(id: params[:id], token: access_token)
    @widgets = Kaminari.paginate_array(@user.widgets(access_token)).page(params[:page])
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def new
    @widget = Widget.new
  end

  def index
    @widgets = Widget.get_visible(params[:term])
    @widgets = Kaminari.paginate_array(@widgets).page(params[:page])
  end

  def edit
    @widget = Widget.show(id: params[:id], token: access_token)
    render 'new'
  end

  def create
    @widget = Widget.new(widget_params)
    @widget.user = current_user
    @widget.save(access_token)
  end

  def update
    @widget = Widget.new(widget_params.merge(id: params[:id]))
    @widget.user = current_user
    @widget.update(access_token)
  end

  def destroy
    @widget = Widget.show(id: params[:id], token: access_token)
    @widget.destroy(access_token)
  end

  private

  def widget_params
    params.require(:widget).permit(:name, :description, :kind)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level.to_sym
    when :notice then 'alert alert-info'
    when :success then 'alert alert-success'
    when :error then 'alert alert-error'
    when :alert then 'alert alert-error'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/layouts/_footer.haml
/ Footer
%footer.py-5.bg-dark
  .container
    %p.m-0.text-center.text-white Copyright © Your Website 2019

app/views/layouts/_header.haml
/ Navigation
%nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.fixed-top
  .container
    = link_to 'ShowoffWidgets', root_path, class: 'navbar-brand'
    %button.navbar-toggler{"aria-controls" => "navbarResponsive", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarResponsive", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarResponsive.collapse.navbar-collapse
      %ul.navbar-nav.ml-auto
        - if user_authenticated?
          %li.nav-item.dropdown.active
            %a#navbarDropdown.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              = current_user.name.titleize
            .dropdown-menu{"aria-labelledby" => "navbarDropdown"}
              = link_to 'Profile', user_path(current_user.id), class: 'dropdown-item'
              = link_to 'SignOut', users_sign_out_path, method: :delete, class: 'dropdown-item'
        - else
          %li.nav-item
            %a.btn.btn-primary{:href => "#", data: {toggle: "modal", target: "#signinModal"}} SignIn

app/views/layouts/application.haml
!!!
%html
  %head
    %title ShowoffWidgets
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/header'
    / Page Content
    .container
      - flash.each do |key, value|
        .mt-3{class: "#{flash_class(key)}" }= value
      = yield
    / /.container
    = render 'layouts/footer'
    = render 'shared/signin_modal'
    = render 'shared/signup_modal'

app/views/shared/_signin_modal.haml
#signinModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title SignIn
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = render 'users/sessions/signin_form', user: User.new

app/views/shared/_signup_modal.haml
#signupModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title SignUp
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = render 'users/registrations/signup_form', user: User.new

app/views/users/_profile_card.haml
.card.profile
  .card-body
    .media
      = image_tag user.images[:small_url], class: 'mr-3 w-25'
      .media-body
        %h5.mt-0= user.name.titleize
        .text-secondary
    %hr.margin-bottom-10

app/views/users/show.html.haml
.row.mt-4
  .col-sm-3
    = render 'profile_card', user: @user
  .col-sm-9
    - if current_user.id == @user.id
      .row
        .col
          = button_to 'Add Widget', new_widget_path, method: :get, remote: true, class: 'btn btn-primary mb-2', data: { disable_with: 'Wait..' }
          = render 'widgets/widget_modal', widget: Widget.new
    .row
      .col
        .card
          .card-header
            %h3 Widgets
          .card-body
            #widgetsContainer
              = render 'widgets/widget_list', widgets: @widgets

app/views/widgets/_form.haml
- if widget.errors[:base].any?
  %p.text-danger= "API Error!: #{widget.errors[:base].first}"

= simple_form_for widget, remote: true do |f|
  = f.input :name
  = f.input :description, as: :text
  = f.input :kind, as: :radio_buttons, collection: ['visible', 'hidden']
  .text-right
    = f.button :button, 'Cancel', class: 'btn btn-secondary', "data-dismiss" => "modal"
    = f.button :submit, 'Save', class: 'btn btn-primary'

app/views/widgets/_widget.haml
.col-lg-4.col-md-6.mb-4{id: "widget_#{widget.id}"}
  .card.h-100
    .card-body
      %h4.card-title= widget.name
      %p.card-text= widget.description
    .card-footer.p-1
      .row
        .col
          By
          = link_to widget.user.name&.titleize, user_path(widget.user.id)
        - if widget.owned_by?(current_user)
          .col.text-right
            = link_to edit_widget_path(widget.id), remote: true, title: 'Edit', class: 'mr-1' do
              %i.fa.fa-edit
            = link_to widget_path(widget.id), method: :delete, remote: true, title: 'Remove', data: { confirm: 'Are you sure?' } do
              %i.fa.fa-trash.text-danger

app/views/widgets/_widget_list.haml
.row.text-center
  = render widgets
= paginate widgets

app/views/widgets/_widget_modal.haml
#widgetModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Widget
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body

app/views/widgets/create.js.erb
<% if @widget.errors.any?  %>
  $("#widgetModal .modal-body").html($("<%= j(render 'form', widget: @widget) %>"))
<% else %>
  $('#widgetModal').modal('hide')
  $("#widgetsContainer .row").append($("<%= j(render @widget) %>"))
<% end  %>

app/views/widgets/destroy.js.erb
<% if @widget.errors.empty?  %>
  $("#widgetsContainer #widget_<%= @widget.id %>").remove()
<% end %>

app/views/widgets/index.haml
%header.jumbotron.my-4
  = form_with url: '/', method: :get do
    .form-row.align-items-center
      .col-sm-11
        = text_field_tag :term , params[:term], class: 'form-control', placeholder: 'Search Widgets'
      .col-auto
        = submit_tag 'Search', class: 'btn btn-primary'


#widgetsContainer
  = render 'widget_list', widgets: @widgets

app/views/widgets/index.js.erb
$("#widgetsContainer").html($("<%= j(render 'widget_list', widgets: @widgets) %>"))

app/views/widgets/new.js.erb
$("#widgetModal .modal-body").html($("<%= j(render 'form', widget: @widget) %>"))
$('#widgetModal').modal('show')

app/views/widgets/update.js.erb
<% if @widget.errors.any?  %>
  $("#widgetModal .modal-body").html($("<%= j(render 'form', widget: @widget) %>"))
<% else %>
  $('#widgetModal').modal('hide')
  $("#widgetsContainer #widget_<%= @widget.id %>").replaceWith($("<%= j(render @widget) %>"))
<% end  %>